services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: commitsight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - commitsight-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d commitsight"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/commitsight
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - commitsight-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -lc "npx prisma generate &&
              npx prisma migrate deploy &&
              npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:3001/api
    depends_on:
      - backend
    networks:
      - commitsight-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  commitsight-network:
    driver: bridge
